# Servidor
server.port=8080

# PostgreSQL via Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/ecodescarte_db
spring.datasource.username=ecouser
spring.datasource.password=ecopass
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true